flyway.user=promo_admin
flyway.password=promo_pass
flyway.driver=org.postgresql.Driver
flyway.url=jdbc:postgresql://localhost:5432/promotion_db
flyway.locations=classpath:db/migration/
flyway.cleanDisabled=false